// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
import type { ApiDataResponse, PubKey, Hash, ApiPagingResponse } from './common'

//////////
// source: mobile.go

export interface MobileBundleData {
	bundle_url?: string
	has_native_update_available: boolean
}
export type GetMobileLatestBundleResponse = ApiDataResponse<MobileBundleData>
export interface MobileValidatorDashboardValidatorsRocketPool {
	deposit_amount: string /* decimal.Decimal */
	commission: number /* float64 */ // percentage, 0-1
	status: 'Staking' | 'Dissolved' | 'Prelaunch' | 'Initialized' | 'Withdrawable'
	penalty_count: number /* uint64 */
	is_in_smoothing_pool: boolean
}
export interface MobileValidatorDashboardValidatorsTableRow {
	index: number /* uint64 */
	public_key: PubKey
	group_id: number /* uint64 */
	balance: string /* decimal.Decimal */
	status:
		| 'slashed'
		| 'exited'
		| 'deposited'
		| 'pending'
		| 'slashing_offline'
		| 'slashing_online'
		| 'exiting_offline'
		| 'exiting_online'
		| 'active_offline'
		| 'active_online'
	queue_position?: number /* uint64 */
	withdrawal_credential: Hash
	/**
	 * additional mobile fields
	 */
	is_in_sync_committee: boolean
	is_in_next_sync_committee: boolean
	efficiency: number /* float64 */
	rocket_pool?: MobileValidatorDashboardValidatorsRocketPool
}
export type InternalGetValidatorDashboardMobileValidatorsResponse = ApiPagingResponse<MobileValidatorDashboardValidatorsTableRow>
