// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: search.go

export interface SearchValidator {
  index: number /* uint64 */;
  public_key: string;
}
export interface SearchValidatorList {
  validators: number /* uint64 */[];
}
export interface SearchValidatorsByDepositAddress {
  ens_name?: string;
  deposit_address: string;
  count: number /* uint64 */;
}
export interface SearchValidatorsByWithdrwalCredential {
  ens_name?: string;
  withdrawal_credential: string;
  count: number /* uint64 */;
}
export interface SearchValidatorsByGraffiti {
  graffiti: string;
  count: number /* uint64 */;
}
export interface SearchResult {
  type: string;
  chain_id: number /* uint64 */;
  value: any;
}
export interface InternalPostSearchResponse {
  data: ({ type: 'validator'; chain_id: number; value: SearchValidator } | { type: 'validator_list'; chain_id: number; value: SearchValidatorList } | { type: 'validators_by_deposit_address'; chain_id: number; value: SearchValidatorsByDepositAddress } | { type: 'validators_by_withdrawal_credential'; chain_id: number; value: SearchValidatorsByWithdrwalCredential } | { type: 'validators_by_graffiti'; chain_id: number; value: SearchValidatorsByGraffiti })[];
}
